sonar.organization=soat13
sonar.projectKey=soat13_oficina-serverless
sonar.projectName=oficina-serverless
sonar.host.url=https://sonarcloud.io

sonar.sources=.
sonar.exclusions=**/vendor/**,**/mocks/**,**/*_test.go,**/tests/**,**/scripts/**,**/assets/**,.env*,**/*.md,**/cmd/**,**/views.go,**/repository.go,**/bootstrap/**,**/container/**

sonar.tests=.
sonar.test.inclusions=**/*_test.go

sonar.go.coverage.reportPaths=coverage.out