AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  DbDsn:
    Type: String
    NoEcho: true
  JwtSecret:
    Type: String
    NoEcho: true
  JwtIssuer:
    Type: String
  JwtTtl:
    Type: String
  LambdaRoleArn:
    Type: String
  VpcSubnetIds:
    Type: List<String>
  VpcId:
    Type: String
  RdsSecurityGroupId:
    Type: String
  ExistingRestApiId:
    Type: String

Globals:
  Function:
    Runtime: provided.al2
    Architectures: [arm64]
    Timeout: 10
    MemorySize: 256

Resources:
  IdentityLambdaSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SG for oficina identity lambda
      VpcId: !Ref VpcId
      SecurityGroupIngress: []
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0

  AllowIdentityLambdaToRds5432:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref RdsSecurityGroupId
      IpProtocol: tcp
      FromPort: 5432
      ToPort: 5432
      SourceSecurityGroupId: !Ref IdentityLambdaSecurityGroup
      Description: Allow Identity Lambda to access RDS Postgres on 5432

  IdentityFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      FunctionName: !Sub "IdentityFunction"
      Handler: bootstrap
      Role: !Ref LambdaRoleArn

      VpcConfig:
        SubnetIds: !Ref VpcSubnetIds
        SecurityGroupIds:
          - !Ref IdentityLambdaSecurityGroup

      Environment:
        Variables:
          DB_DSN: !Ref DbDsn
          JWT_SECRET: !Ref JwtSecret
          JWT_ISSUER: !Ref JwtIssuer
          JWT_TTL: !Ref JwtTtl
    Metadata:
      BuildMethod: makefile

  AllowApiGwInvokeIdentityLogin:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref IdentityFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ExistingRestApiId}/*/*"

  IdentityFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${IdentityFunction}"
      RetentionInDays: 14

Outputs:
  IdentityLambdaSecurityGroupId:
    Description: SG ID created for Identity Lambda
    Value: !Ref IdentityLambdaSecurityGroup