name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ "*" ]

jobs:
  tests-and-quality:
    name: Tests & Quality
    runs-on: ubuntu-latest

    env:
      DB_DSN: postgres://auth:auth@127.0.0.1:5432/auth?sslmode=disable

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: auth
          POSTGRES_PASSWORD: auth
          POSTGRES_DB: auth
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U auth -d auth"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=20

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Download dependencies
        run: go mod download

      - name: Install PostgreSQL client
        run: sudo apt-get update && sudo apt-get install -y postgresql-client

      - name: Wait for Postgres
        run: |
          until pg_isready -h 127.0.0.1 -p 5432 -U auth -d auth; do
            echo "waiting postgres..."
            sleep 1
          done

      - name: Run tests with coverage
        run: |
          go test -v ./... \
            -covermode=atomic \
            -coverpkg=./... \
            -coverprofile=coverage.out

      - name: Show coverage summary
        run: go tool cover -func=coverage.out | tail -n 20

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@fd88b7d7ccbaefd23d8f36f73b59db7a3d246602
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: >
            -Dsonar.go.coverage.reportPaths=coverage.out
