name: ci-cd

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ "*" ]

jobs:
  tests-and-quality:
    name: Tests & Quality
    runs-on: ubuntu-latest

    env:
      DB_DSN: postgres://auth:auth@127.0.0.1:5432/auth?sslmode=disable

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: auth
          POSTGRES_PASSWORD: auth
          POSTGRES_DB: auth
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U auth -d auth"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=20

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Download dependencies
        run: go mod download

      - name: Install PostgreSQL client
        run: sudo apt-get update && sudo apt-get install -y postgresql-client

      - name: Wait for Postgres
        run: |
          until pg_isready -h 127.0.0.1 -p 5432 -U auth -d auth; do
            echo "waiting postgres..."
            sleep 1
          done

      - name: Run tests with coverage
        run: |
          go test -v ./... \
            -covermode=atomic \
            -coverpkg=./... \
            -coverprofile=coverage.out

      - name: Show coverage summary
        run: go tool cover -func=coverage.out | tail -n 20

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@fd88b7d7ccbaefd23d8f36f73b59db7a3d246602
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: >
            -Dsonar.go.coverage.reportPaths=coverage.out

  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    needs: [ tests-and-quality ]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "1.22.x"

      - uses: aws-actions/setup-sam@d78e1a4a9656d3b223e59b80676a797f20093133

      - uses: aws-actions/configure-aws-credentials@8df5847569e6427dd6c4fb1cf565c83acfa8afa7
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Build
        run: sam build -t template.yaml

      - name: Deploy
        env:
          DB_DSN: ${{ secrets.DB_DSN }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          JWT_ISSUER: ${{ secrets.JWT_ISSUER }}
          JWT_TTL: ${{ secrets.JWT_TTL }}
          LAMBDA_ROLE_ARN: ${{ secrets.LAMBDA_ROLE_ARN }}

          VPC_ID: ${{ secrets.VPC_ID }}
          VPC_SUBNET_IDS: ${{ secrets.VPC_SUBNET_IDS }}
          RDS_SECURITY_GROUP_ID: ${{ secrets.RDS_SECURITY_GROUP_ID }}
          EXISTING_REST_API_ID: ${{ secrets.EXISTING_REST_API_ID }}
        run: |
          sam deploy \
            --stack-name oficina-serverless-v2 \
            --capabilities CAPABILITY_IAM \
            --no-fail-on-empty-changeset \
            --resolve-s3 \
            --parameter-overrides \
              DbDsn="$DB_DSN" \
              JwtSecret="$JWT_SECRET" \
              JwtIssuer="$JWT_ISSUER" \
              JwtTtl="$JWT_TTL" \
              LambdaRoleArn="$LAMBDA_ROLE_ARN" \
              VpcId="$VPC_ID" \
              VpcSubnetIds="$VPC_SUBNET_IDS" \
              RdsSecurityGroupId="$RDS_SECURITY_GROUP_ID" \
              ExistingRestApiId="$EXISTING_REST_API_ID"

      - name: Show Lambda info
        run: |
          STACK=oficina-serverless
          aws cloudformation describe-stacks --stack-name "$STACK" --query "Stacks[0].StackStatus" --output text
          echo "Lambda function name: IdentityFunction"